//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 活动表
    /// </summary>
    public partial class Activity
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long ActivityId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? UserID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string UserName { get; set; }
    
    	/// <summary>
    	/// 活动 标题
    	/// </summary>
        public string Title { get; set; }
    
    	/// <summary>
    	/// 活动内容
    	/// </summary>
        public string Body { get; set; }
    
    	/// <summary>
    	/// 活动海报
    	/// </summary>
        public string ActivityIMG { get; set; }
    
    	/// <summary>
    	/// 活动形式(线上 1 线下 2）
    	/// </summary>
        public int? ActivityType { get; set; }
    
    	/// <summary>
    	/// 活动地点
    	/// </summary>
        public string Address { get; set; }
    
    	/// <summary>
    	/// 活动开始时间
    	/// </summary>
        public System.DateTime? BeginTime { get; set; }
    
    	/// <summary>
    	/// 活动结束时间
    	/// </summary>
        public System.DateTime? EndTime { get; set; }
    
    	/// <summary>
    	/// 活动开始之前均可报名(1 可，2 手动设置报名开始截止时间）
    	/// </summary>
        public int? CanJoinOnBegin { get; set; }
    
    	/// <summary>
    	/// 活动报名开始时间
    	/// </summary>
        public System.DateTime? JoinBeginTime { get; set; }
    
    	/// <summary>
    	/// 活动报名结束时间
    	/// </summary>
        public System.DateTime? JoinEndTime { get; set; }
    
    	/// <summary>
    	/// 活动创建时间
    	/// </summary>
        public System.DateTime? ActivityCreateTIme { get; set; }
    
    	/// <summary>
    	/// 浏览量
    	/// </summary>
        public long? PVCount { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 需要审核（ 1  未审核  2 不需要审核/已审核 3 审核不通过 ）--用户发布的活动要审核
    	/// </summary>
        public int? IsChecked { get; set; }
    
    }
}
