//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 广告
    /// </summary>
    public partial class AD
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long ADID { get; set; }
    
    	/// <summary>
    	/// 广告图片
    	/// </summary>
        public string ADIMG { get; set; }
    
    	/// <summary>
    	/// 广告标题
    	/// </summary>
        public string ADTitle { get; set; }
    
    	/// <summary>
    	/// 广告描述
    	/// </summary>
        public string ADMsg { get; set; }
    
    	/// <summary>
    	/// 广告联系方式
    	/// </summary>
        public string ADContact { get; set; }
    
    	/// <summary>
    	/// 广告微信号
    	/// </summary>
        public string ADWeChat { get; set; }
    
    	/// <summary>
    	/// 广告点击次数
    	/// </summary>
        public int? ADViewCount { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
