//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Common;
    
    public partial class AmazonBBSDBContext : DbContext
    {
    
    	public AmazonBBSDBContext(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
        public AmazonBBSDBContext()
            : base("name=AmazonBBSDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityFee> ActivityFee { get; set; }
        public virtual DbSet<ActivityJoin> ActivityJoin { get; set; }
        public virtual DbSet<AD> AD { get; set; }
        public virtual DbSet<Against> Against { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<AttachMent> AttachMent { get; set; }
        public virtual DbSet<AttachMentBuyLog> AttachMentBuyLog { get; set; }
        public virtual DbSet<AutoReply> AutoReply { get; set; }
        public virtual DbSet<AutoReplyItem> AutoReplyItem { get; set; }
        public virtual DbSet<BBSEnum> BBSEnum { get; set; }
        public virtual DbSet<BuyOtherLog> BuyOtherLog { get; set; }
        public virtual DbSet<BXTOrder> BXTOrder { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<ClickMsg> ClickMsg { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<ContentBuyLog> ContentBuyLog { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<EditLog> EditLog { get; set; }
        public virtual DbSet<EmailNotice> EmailNotice { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<Express> Express { get; set; }
        public virtual DbSet<FeeAnswerLog> FeeAnswerLog { get; set; }
        public virtual DbSet<FeeHR> FeeHR { get; set; }
        public virtual DbSet<Gift> Gift { get; set; }
        public virtual DbSet<GiftFee> GiftFee { get; set; }
        public virtual DbSet<InviteInterview> InviteInterview { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobComment> JobComment { get; set; }
        public virtual DbSet<JobTrade> JobTrade { get; set; }
        public virtual DbSet<JoinItemAnswerExt> JoinItemAnswerExt { get; set; }
        public virtual DbSet<JoinItemQuestionExt> JoinItemQuestionExt { get; set; }
        public virtual DbSet<LeaveWord> LeaveWord { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<MenuBelongTag> MenuBelongTag { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<OAuth> OAuth { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderCheck> OrderCheck { get; set; }
        public virtual DbSet<OrderSend> OrderSend { get; set; }
        public virtual DbSet<PayCBLog> PayCBLog { get; set; }
        public virtual DbSet<Prise> Prise { get; set; }
        public virtual DbSet<PrivateKey> PrivateKey { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductBuy> ProductBuy { get; set; }
        public virtual DbSet<QiuZhi> QiuZhi { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ScoreBeloneItem> ScoreBeloneItem { get; set; }
        public virtual DbSet<ScoreCoinLog> ScoreCoinLog { get; set; }
        public virtual DbSet<SendCV> SendCV { get; set; }
        public virtual DbSet<ShareLink> ShareLink { get; set; }
        public virtual DbSet<ShareRegistLog> ShareRegistLog { get; set; }
        public virtual DbSet<ShipAddress> ShipAddress { get; set; }
        public virtual DbSet<SiteHead> SiteHead { get; set; }
        public virtual DbSet<SiteNotice> SiteNotice { get; set; }
        public virtual DbSet<Slide> Slide { get; set; }
        public virtual DbSet<SoftLink> SoftLink { get; set; }
        public virtual DbSet<SoftLinkType> SoftLinkType { get; set; }
        public virtual DbSet<StudyClass> StudyClass { get; set; }
        public virtual DbSet<StudyShareImgSet> StudyShareImgSet { get; set; }
        public virtual DbSet<StudyUnit> StudyUnit { get; set; }
        public virtual DbSet<SuggestSite> SuggestSite { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<UserBase> UserBase { get; set; }
        public virtual DbSet<UserDisabledLog> UserDisabledLog { get; set; }
        public virtual DbSet<UserExt> UserExt { get; set; }
        public virtual DbSet<UserGift> UserGift { get; set; }
        public virtual DbSet<UserLike> UserLike { get; set; }
        public virtual DbSet<UserLoginLog> UserLoginLog { get; set; }
        public virtual DbSet<UserScore> UserScore { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
        public virtual DbSet<UserShareLog> UserShareLog { get; set; }
        public virtual DbSet<UserStudy> UserStudy { get; set; }
        public virtual DbSet<VIPHead> VIPHead { get; set; }
        public virtual DbSet<ZhaoPin> ZhaoPin { get; set; }
    }
}
