//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 回答表
    /// </summary>
    public partial class Answer
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long AnswerId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? QuestionId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? AnswerUserId { get; set; }
    
    	/// <summary>
    	/// 答案
    	/// </summary>
        public string AnswerContent { get; set; }
    
    	/// <summary>
    	/// 是否设置显示或隐藏指定可见范围
    	/// </summary>
        public int? IsCanSee { get; set; }
    
    	/// <summary>
    	/// 可见类型消费(1 积分 2金钱）
    	/// </summary>
        public int? CoinType { get; set; }
    
    	/// <summary>
    	/// 可见需要数值
    	/// </summary>
        public int? NeedCoin { get; set; }
    
    	/// <summary>
    	/// 评论还是回复(1 评论 2 回复)
    	/// </summary>
        public int? AType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? UpdateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string UpdateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? ReplyTopAnswerId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? ReplyToUserID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? ReplyToAnswerID { get; set; }
    
    }
}
