//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 附件
    /// </summary>
    public partial class AttachMent
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid AttachMentId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long MainId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int MainType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string FileName { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string FilePath { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string FileSize { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int DownCount { get; set; }
    
    	/// <summary>
    	/// 是否需要付费查看
    	/// </summary>
        public bool IsFee { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int Fee { get; set; }
    
    	/// <summary>
    	/// 付费类型（1积分 2金钱）
    	/// </summary>
        public int FeeType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int IsDelete { get; set; }
    
    }
}
