//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 自动回复关键字值
    /// </summary>
    public partial class AutoReplyItem
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long AutoReplyItemId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid AutoReplyId { get; set; }
    
    	/// <summary>
    	/// 替换关键字
    	/// </summary>
        public string ReplaceKey { get; set; }
    
    	/// <summary>
    	/// 替换值
    	/// </summary>
        public string ReplaceValue { get; set; }
    
    	/// <summary>
    	/// 替换关键字分组---为了某些自动回复模板有不同个的关键字组合
    	/// </summary>
        public int GroupId { get; set; }
    
    	/// <summary>
    	/// 是否使用
    	/// </summary>
        public bool IsUsed { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int IsDelete { get; set; }
    
    }
}
