//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 枚举
    /// </summary>
    public partial class BBSEnum
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int BBSEnumId { get; set; }
    
    	/// <summary>
    	/// 枚举类型 (1菜单 )
    	/// </summary>
        public int? EnumType { get; set; }
    
    	/// <summary>
    	/// 枚举描述
    	/// </summary>
        public string EnumDesc { get; set; }
    
    	/// <summary>
    	/// 枚举代号
    	/// </summary>
        public string EnumCode { get; set; }
    
    	/// <summary>
    	/// 默认Url
    	/// </summary>
        public string Url { get; set; }
    
    	/// <summary>
    	/// 是否论坛页面
    	/// </summary>
        public int? IsBBS { get; set; }
    
    	/// <summary>
    	/// 显示顺序 1 2 3 4 5
    	/// </summary>
        public int? SortIndex { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? UpdateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string UpdateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? CanArticle { get; set; }
    
    	/// <summary>
    	/// 字体颜色
    	/// </summary>
        public string FontColor { get; set; }
    
    	/// <summary>
    	/// 字体底色
    	/// </summary>
        public string FontBGColor { get; set; }
    
    	/// <summary>
    	/// 页面底色
    	/// </summary>
        public string PageBGColor { get; set; }
    
    	/// <summary>
    	/// 菜单分组
    	/// </summary>
        public int? GroupBy { get; set; }
    
    }
}
