//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户购买other帖子记录表
    /// </summary>
    public partial class BuyOtherLog
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int BuyOtherLogId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long MainID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int Fee { get; set; }
    
    }
}
