//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 鼠标点击提示语
    /// </summary>
    public partial class ClickMsg
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid ClickMsgId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Msg { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Msg_en { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Color { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? UpdateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string UpdateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
