//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 修改限制记录表
    /// </summary>
    public partial class EditLog
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long EditLogId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? UserID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string OldValue { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string NewValue { get; set; }
    
    	/// <summary>
    	/// 类型：1修改昵称(1个月只能修改一次)
    	/// </summary>
        public int? Type { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    }
}
