//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 
    /// </summary>
    public partial class ErrorLog
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long ErrorLogID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ErrorMsg { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? ErrorTime { get; set; }
    
    }
}
