//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 物流
    /// </summary>
    public partial class Express
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int ExpressId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long UserGiftId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ExpressNo { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ExpressName { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int ExpressType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int IsDelete { get; set; }
    
    }
}
