//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 礼物表
    /// </summary>
    public partial class Gift
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long GiftID { get; set; }
    
    	/// <summary>
    	/// 礼物名称
    	/// </summary>
        public string GiftName { get; set; }
    
    	/// <summary>
    	/// 礼物价格
    	/// </summary>
        public decimal? GiftPrise { get; set; }
    
    	/// <summary>
    	/// 礼物价格类型（1积分 2金钱）
    	/// </summary>
        public int? GiftPriseType { get; set; }
    
    	/// <summary>
    	/// 礼物简介
    	/// </summary>
        public string GiftDesc { get; set; }
    
    	/// <summary>
    	/// 礼物详细介绍
    	/// </summary>
        public string GiftInfo { get; set; }
    
    	/// <summary>
    	/// 礼物剩余数量
    	/// </summary>
        public int? GiftCount { get; set; }
    
    	/// <summary>
    	/// 礼物图片
    	/// </summary>
        public string GiftImgs { get; set; }
    
    	/// <summary>
    	/// 浏览量
    	/// </summary>
        public long? PVCount { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? GiftCreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? GiftCreateUserID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 兑换类型(1-礼物 2-数据分析 3-百晓堂课程)
    	/// </summary>
        public int? GType { get; set; }
    
    	/// <summary>
    	/// 购买时是否填写资料(1 填写  0不填写）
    	/// </summary>
        public int? OpenJoinItem { get; set; }
    
    }
}
