//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 邀请面试记录表
    /// </summary>
    public partial class InviteInterview
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long InviteInterviewId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? ZhaoPinID { get; set; }
    
    	/// <summary>
    	/// 面试时间
    	/// </summary>
        public System.DateTime? InviteTime { get; set; }
    
    	/// <summary>
    	/// 面试地址
    	/// </summary>
        public string ViewAddress { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? QiuZhiID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? QiuZhiPublisher { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
