//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 职位
    /// </summary>
    public partial class Job
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid JobId { get; set; }
    
    	/// <summary>
    	/// 职位分类名称
    	/// </summary>
        public string JobType { get; set; }
    
    	/// <summary>
    	/// 职位名称
    	/// </summary>
        public string JobName { get; set; }
    
    	/// <summary>
    	/// 对应职位分类
    	/// </summary>
        public System.Guid? ParentJobId { get; set; }
    
    	/// <summary>
    	/// 是否职位分类
    	/// </summary>
        public int? IsJobType { get; set; }
    
    	/// <summary>
    	/// 是否职位
    	/// </summary>
        public int? IsJob { get; set; }
    
    	/// <summary>
    	/// 创建类型
    	/// </summary>
        public int? CreateType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
