//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 工作评论
    /// </summary>
    public partial class JobComment
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long JobCommentID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? MainID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Comment { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateHeadUrl { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateNickName { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 评论类型（1：招聘 2：求职）
    	/// </summary>
        public int? CommentType { get; set; }
    
    }
}
