//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 行业
    /// </summary>
    public partial class JobTrade
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid JobTradeId { get; set; }
    
    	/// <summary>
    	/// 行业名称
    	/// </summary>
        public string JobTradeName { get; set; }
    
    	/// <summary>
    	/// 创建类型（1后台管理员增加 2用户增加）
    	/// </summary>
        public int? CreateType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
