//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 报名购买选项回答表
    /// </summary>
    public partial class JoinItemAnswerExt
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long JoinItemAnswerExtId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? JoinItemQuestionExtId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? JoinMainID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? JoinType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? BuyerID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ItemAnswer { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    }
}
