//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 客服留言
    /// </summary>
    public partial class LeaveWord
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long LeaveWordId { get; set; }
    
    	/// <summary>
    	/// 电话
    	/// </summary>
        public string Telephone { get; set; }
    
    	/// <summary>
    	/// 称呼
    	/// </summary>
        public string Name { get; set; }
    
    	/// <summary>
    	/// 年龄
    	/// </summary>
        public int? Age { get; set; }
    
    	/// <summary>
    	/// 自定义一
    	/// </summary>
        public string DIY1 { get; set; }
    
    	/// <summary>
    	/// 自定义二
    	/// </summary>
        public string DIY2 { get; set; }
    
    	/// <summary>
    	/// 自定义三
    	/// </summary>
        public string DIY3 { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
