//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 公司新闻
    /// </summary>
    public partial class News
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long NewsID { get; set; }
    
    	/// <summary>
    	/// 新闻标题
    	/// </summary>
        public string NTitle { get; set; }
    
    	/// <summary>
    	/// 新闻内容
    	/// </summary>
        public string NBody { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsTop { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 浏览量
    	/// </summary>
        public long? PVCount { get; set; }
    
    }
}
