//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 第三方登录
    /// </summary>
    public partial class OAuth
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long OAuthID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? UserID { get; set; }
    
    	/// <summary>
    	/// 登录类型（1QQ 3微信)
    	/// </summary>
        public int? OAuthType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string OpenId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string NickName { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string HeadUrl { get; set; }
    
    	/// <summary>
    	/// 是否绑定(1已绑定 0未绑定)
    	/// </summary>
        public int? IsBind { get; set; }
    
    }
}
