//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 发货状态(0 未发货 1 已发货 。。。可能还有后续状态 分批发货等)
    /// </summary>
    public partial class OrderSend
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int OrderSendId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long OrderID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long UserGiftId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long MainID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long MainType { get; set; }
    
    	/// <summary>
    	/// 是否发货(0未发货 1 已发货 。。。)
    	/// </summary>
        public int SendStatus { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime UpdateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long UpdateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int IsDelete { get; set; }
    
    }
}
