//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 收货状态
    /// </summary>
    public partial class OrderCheck
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int OrderCheckId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long OrderID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long UserGiftId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long MainID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long MainType { get; set; }
    
    	/// <summary>
    	/// 收货状态（0 未确认收货 1 已确认收货 2 退款中 3 已退款）
    	/// </summary>
        public int CheckStatus { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime UpdateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long UpdateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int IsDelete { get; set; }
    
    }
}
