//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 支付回调日志
    /// </summary>
    public partial class PayCBLog
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long PayCBLogID { get; set; }
    
    	/// <summary>
    	/// 回调时间
    	/// </summary>
        public System.DateTime? CallBackTime { get; set; }
    
    	/// <summary>
    	/// 商品订单号
    	/// </summary>
        public string TradeNo { get; set; }
    
    	/// <summary>
    	/// 是否支付成功
    	/// </summary>
        public int? IsPay { get; set; }
    
    	/// <summary>
    	/// 交易状态
    	/// </summary>
        public string TradeStatus { get; set; }
    
    	/// <summary>
    	/// 日志信息
    	/// </summary>
        public string Memo { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
