//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 点赞表
    /// </summary>
    public partial class Prise
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long PriseId { get; set; }
    
    	/// <summary>
    	/// 被赞目标ID（问题，文章，评论/回复）
    	/// </summary>
        public long? TargetID { get; set; }
    
    	/// <summary>
    	/// 类型（ 1、问题 2、问题的评论回复 3、文章 4、文章的评论回复 5、活动 6、活动的评论回复 7、礼物 8、礼物的评论回复 9、招聘 10、招聘的评论回复 11、求职 12、求职的评论回复 13、产品服务 14、产品服务的评论回复 15、数据分析 16、数据分析的评论回复 17、课程 18、课程的评论回复）
    	/// </summary>
        public int? Type { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? UserID { get; set; }
    
    	/// <summary>
    	/// 点赞时间
    	/// </summary>
        public System.DateTime? PriseTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
