//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 采集器私钥生成表
    /// </summary>
    public partial class PrivateKey
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int PrivateKeyId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ProtectKey { get; set; }
    
    	/// <summary>
    	/// 当前时间戳
    	/// </summary>
        public string timespan { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string userID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int IsDelete { get; set; }
    
    }
}
