//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 产品预约购买记录
    /// </summary>
    public partial class ProductBuy
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long ProductBuyId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? ProductID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? BuyUserID { get; set; }
    
    	/// <summary>
    	/// 联系人
    	/// </summary>
        public string LinkName { get; set; }
    
    	/// <summary>
    	/// 联系电话
    	/// </summary>
        public string LinkTel { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
