//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 产品服务
    /// </summary>
    public partial class Product
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long ProductID { get; set; }
    
    	/// <summary>
    	/// 产品图片
    	/// </summary>
        public string PLogo { get; set; }
    
    	/// <summary>
    	/// 产品标题
    	/// </summary>
        public string PTitle { get; set; }
    
    	/// <summary>
    	/// 产品定位
    	/// </summary>
        public string PLocation { get; set; }
    
    	/// <summary>
    	/// 产品介绍
    	/// </summary>
        public string PDesc { get; set; }
    
    	/// <summary>
    	/// 产品功能
    	/// </summary>
        public string PFunction { get; set; }
    
    	/// <summary>
    	/// 产品价格
    	/// </summary>
        public int? PPrice { get; set; }
    
    	/// <summary>
    	/// 尺寸重量
    	/// </summary>
        public string PSize { get; set; }
    
    	/// <summary>
    	/// 公司名称
    	/// </summary>
        public string CompanyName { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 浏览量
    	/// </summary>
        public long? PVCount { get; set; }
    
    	/// <summary>
    	/// 产品图片
    	/// </summary>
        public string ProductPic { get; set; }
    
    	/// <summary>
    	/// 联系方式
    	/// </summary>
        public string Contact { get; set; }
    
    	/// <summary>
    	/// 精华
    	/// </summary>
        public int? IsJinghua { get; set; }
    
    	/// <summary>
    	/// 热门
    	/// </summary>
        public int? IsRemen { get; set; }
    
    	/// <summary>
    	/// 置顶
    	/// </summary>
        public int? IsTop { get; set; }
    
    	/// <summary>
    	/// 更新人
    	/// </summary>
        public string UpdateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? UpdateTime { get; set; }
    
    	/// <summary>
    	/// 发货天数
    	/// </summary>
        public int? SendDay { get; set; }
    
    	/// <summary>
    	/// 产品重量
    	/// </summary>
        public string PWeight { get; set; }
    
    	/// <summary>
    	/// 产品单位
    	/// </summary>
        public int? PUnit { get; set; }
    
    	/// <summary>
    	/// 有效时间
    	/// </summary>
        public System.DateTime? ValidTime { get; set; }
    
    }
}
