//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 提问表
    /// </summary>
    public partial class Question
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long QuestionId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? UserID { get; set; }
    
    	/// <summary>
    	/// 标题
    	/// </summary>
        public string Title { get; set; }
    
    	/// <summary>
    	/// 内容主体
    	/// </summary>
        public string Body { get; set; }
    
    	/// <summary>
    	/// 所属分类
    	/// </summary>
        public int? TopicID { get; set; }
    
    	/// <summary>
    	/// 悬赏积分
    	/// </summary>
        public int? Coin { get; set; }
    
    	/// <summary>
    	/// 悬赏类型(1积分 2金钱)
    	/// </summary>
        public int? CoinType { get; set; }
    
    	/// <summary>
    	/// 浏览量
    	/// </summary>
        public int? PVCount { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? UpdateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string UpdateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? BestAnswerId { get; set; }
    
    	/// <summary>
    	/// 精华贴
    	/// </summary>
        public int? IsJinghua { get; set; }
    
    	/// <summary>
    	/// 热门贴
    	/// </summary>
        public int? IsRemen { get; set; }
    
    	/// <summary>
    	/// 置顶贴
    	/// </summary>
        public int? IsTop { get; set; }
    
    	/// <summary>
    	/// 需要审核（0  不需要审核 1  未审核  2 已审核 ）
    	/// </summary>
        public int? IsChecked { get; set; }
    
    	/// <summary>
    	/// 优秀回答
    	/// </summary>
        public long? NiceAnswerId { get; set; }
    
    	/// <summary>
    	/// 修改次数
    	/// </summary>
        public int? EditCount { get; set; }
    
    	/// <summary>
    	/// 附件路径
    	/// </summary>
        public string FilePath { get; set; }
    
    	/// <summary>
    	/// 内容需要付费
    	/// </summary>
        public bool? ContentNeedPay { get; set; }
    
    	/// <summary>
    	/// 付费类型（10积分 20金钱）
    	/// </summary>
        public int? ContentFeeType { get; set; }
    
    	/// <summary>
    	/// 内容费用
    	/// </summary>
        public int? ContentFee { get; set; }
    
    	/// <summary>
    	/// 是否匿名发布
    	/// </summary>
        public bool IsAnonymous { get; set; }
    
    }
}
