//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 举报
    /// </summary>
    public partial class Report
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid ReportId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long MainId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int MainType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Desc { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int IsDelete { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public bool IsHandle { get; set; }
    
    }
}
