//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 积分金钱流水表
    /// </summary>
    public partial class ScoreCoinLog
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long ScoreCoinLogId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long UserID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string UserName { get; set; }
    
    	/// <summary>
    	/// 类型（1积分 2金钱）
    	/// </summary>
        public int CoinType { get; set; }
    
    	/// <summary>
    	/// 积分/金钱(如：20 ， -20）
    	/// </summary>
        public int Coin { get; set; }
    
    	/// <summary>
    	/// 变动渠道来源(如  1充值，2回答赠送，3签到赠送）
    	/// </summary>
        public int CoinSource { get; set; }
    
    	/// <summary>
    	/// 变动时间
    	/// </summary>
        public System.DateTime CoinTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    }
}
