//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 分享链接表
    /// </summary>
    public partial class ShareLink
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long ShareLinkID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? UserID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ShareOpenId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ShareToken { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ShareMd5Key { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ShareAddress { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? PVCount { get; set; }
    
    }
}
