//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 收件地址信息
    /// </summary>
    public partial class ShipAddress
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid ShipAddressId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long UserID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ReceiveName { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string WeChatNo { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string ReceiveAddress { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Tel { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public bool IsDefault { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int IsDelete { get; set; }
    
    }
}
