//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 首页轮播管理
    /// </summary>
    public partial class Slide
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int SlideId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Title { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Img { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Url { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? EndTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 字段颜色
    	/// </summary>
        public string FontColor { get; set; }
    
    	/// <summary>
    	/// 轮播类型 11 左侧   21 右上 22 右下
    	/// </summary>
        public int? SlideType { get; set; }
    
    }
}
