//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 软件导航
    /// </summary>
    public partial class SoftLink
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int SoftLinkID { get; set; }
    
    	/// <summary>
    	/// 导航分类
    	/// </summary>
        public int? SoftLinkType { get; set; }
    
    	/// <summary>
    	/// 链接名称
    	/// </summary>
        public string LinkName { get; set; }
    
    	/// <summary>
    	/// 链接地址
    	/// </summary>
        public string LinkAddress { get; set; }
    
    	/// <summary>
    	/// 链接说明
    	/// </summary>
        public string LinkMemo { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 浏览量
    	/// </summary>
        public long? PVCount { get; set; }
    
    }
}
