//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 导航分类
    /// </summary>
    public partial class SoftLinkType
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int SoftLinkTypeID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string SoftLinkTypeName { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 导航名颜色
    	/// </summary>
        public string SoftLinkColor { get; set; }
    
    	/// <summary>
    	/// 导航logo
    	/// </summary>
        public string SoftLinkLogo { get; set; }
    
    }
}
