//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 学习表-课时
    /// </summary>
    public partial class StudyClass
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid StudyClassId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid StudyUnitId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Name { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int SortIndex { get; set; }
    
    	/// <summary>
    	/// 学习内容
    	/// </summary>
        public string Content { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int IsDelete { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    }
}
