//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 标签
    /// </summary>
    public partial class Tag
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long TagId { get; set; }
    
    	/// <summary>
    	/// 标签名
    	/// </summary>
        public string TagName { get; set; }
    
    	/// <summary>
    	/// 标签创建类型（1-系统标签 2-用户创建标签）
    	/// </summary>
        public int? TagCreateType { get; set; }
    
    	/// <summary>
    	/// 标签所属菜单分类(如所属推广、文章等ID )
    	/// </summary>
        public int? TagBelongId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
