//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户兑换礼物表
    /// </summary>
    public partial class UserGift
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long UserGiftId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? GiftID { get; set; }
    
    	/// <summary>
    	/// 购买者
    	/// </summary>
        public long? BuyUserID { get; set; }
    
    	/// <summary>
    	/// 购买时间
    	/// </summary>
        public System.DateTime? BuyTime { get; set; }
    
    	/// <summary>
    	/// 购买数量
    	/// </summary>
        public int? BuyCount { get; set; }
    
    	/// <summary>
    	/// 兑换类型(1-礼物 2-数据分析 3-百晓堂课程)
    	/// </summary>
        public int? GType { get; set; }
    
    	/// <summary>
    	/// 兑换类型(1-礼物 2-数据分析 3-百晓堂课程)
    	/// </summary>
        public long? GiftFeeId { get; set; }
    
    	/// <summary>
    	/// 费用类型 （0免费 10积分 20VIP分 30现金）
    	/// </summary>
        public decimal? Fee { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? FeeType { get; set; }
    
    	/// <summary>
    	/// 是否付费
    	/// </summary>
        public int? IsPay { get; set; }
    
    	/// <summary>
    	/// 联系人
    	/// </summary>
        public string LinkMan { get; set; }
    
    	/// <summary>
    	/// 联系电话
    	/// </summary>
        public string LinkTel { get; set; }
    
    }
}
