//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 关注列表
    /// </summary>
    public partial class UserLike
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long UserLikeId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? UserID { get; set; }
    
    	/// <summary>
    	/// 关注的目标ID（问题，文章，评论/回复）
    	/// </summary>
        public long? LikeTargetID { get; set; }
    
    	/// <summary>
    	/// 类型（1 问题 2 评论、回复 3、文章）
    	/// </summary>
        public long? LikeType { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? LikeTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
