//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户基本表
    /// </summary>
    public partial class UserBase
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long UserID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string UserName { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Account { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Password { get; set; }
    
    	/// <summary>
    	/// 注册来源（1QQ登录 2邮箱注册 3微信登录)
    	/// </summary>
        public int? Source { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CreateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? UpdateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string UpdateUser { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Sign { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string HeadUrl { get; set; }
    
    	/// <summary>
    	/// 性别
    	/// </summary>
        public int? Gender { get; set; }
    
    	/// <summary>
    	/// 所在省
    	/// </summary>
        public string Province { get; set; }
    
    	/// <summary>
    	/// 所在市
    	/// </summary>
        public string City { get; set; }
    
    	/// <summary>
    	/// 所在县
    	/// </summary>
        public string County { get; set; }
    
    	/// <summary>
    	/// 出生年月日
    	/// </summary>
        public string Birth { get; set; }
    
    	/// <summary>
    	/// 岗位
    	/// </summary>
        public string Work { get; set; }
    
    	/// <summary>
    	/// 经营类目
    	/// </summary>
        public string JingYing { get; set; }
    
    	/// <summary>
    	/// 工作年限
    	/// </summary>
        public string WorkYear { get; set; }
    
    	/// <summary>
    	/// 登录时间
    	/// </summary>
        public System.DateTime? LoginTime { get; set; }
    
    	/// <summary>
    	/// 登录IP地址
    	/// </summary>
        public string LoginIP { get; set; }
    
    	/// <summary>
    	/// 第三方登录ID
    	/// </summary>
        public string OpenId { get; set; }
    
    }
}
