//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 标签会员分享记录
    /// </summary>
    public partial class UserShareLog
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int UserShareLogId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime ShareTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.Guid ClassId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public bool IsDelete { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string Url { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? UseImage { get; set; }
    
    }
}
