//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户扩展表
    /// </summary>
    public partial class UserExt
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long UserExtId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? UserID { get; set; }
    
    	/// <summary>
    	/// 剩余总积分
    	/// </summary>
        public int? TotalScore { get; set; }
    
    	/// <summary>
    	/// 剩余总金钱
    	/// </summary>
        public int? TotalCoin { get; set; }
    
    	/// <summary>
    	/// 用户头衔
    	/// </summary>
        public int? LevelName { get; set; }
    
    	/// <summary>
    	/// 用户专属头衔
    	/// </summary>
        public int? OnlyLevelName { get; set; }
    
    	/// <summary>
    	/// 用户封禁到期时间
    	/// </summary>
        public System.DateTime? CloseTime { get; set; }
    
    	/// <summary>
    	/// 用户认证(1:1级认证，2:2级认证 3：3级认证 4：1级和2级认证 5：2级和3级认证 6：1级和3级认证)
    	/// </summary>
        public int? UserV { get; set; }
    
    	/// <summary>
    	/// 真实姓名
    	/// </summary>
        public string RealName { get; set; }
    
    	/// <summary>
    	/// 身份证号码
    	/// </summary>
        public string CardID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string CardPic { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string FaRenPic { get; set; }
    
    	/// <summary>
    	/// 公司名称
    	/// </summary>
        public string CompanyName { get; set; }
    
    	/// <summary>
    	/// 公司联系电话
    	/// </summary>
        public string CompanyTel { get; set; }
    
    	/// <summary>
    	/// VIP等级（1，2，3……等级无上限）
    	/// </summary>
        public int? VIP { get; set; }
    
    	/// <summary>
    	/// VIP有效时间
    	/// </summary>
        public System.DateTime? VIPExpiryTime { get; set; }
    
    	/// <summary>
    	/// 头衔显示类型(1头衔(默认)   2专属头衔)
    	/// </summary>
        public int? HeadNameShowType { get; set; }
    
    	/// <summary>
    	/// 发贴需要审核
    	/// </summary>
        public int? CheckBBS { get; set; }
    
    	/// <summary>
    	/// 用户个人中心皮肤
    	/// </summary>
        public string UserCenterSkin { get; set; }
    
    	/// <summary>
    	/// 用户总签到次数
    	/// </summary>
        public int? UserSignTotalCount { get; set; }
    
    	/// <summary>
    	/// 用户总连续签到次数
    	/// </summary>
        public int? UserSignContinueCount { get; set; }
    
    	/// <summary>
    	/// 用户本月连续签到次数
    	/// </summary>
        public int? UserMonthSignContinueCount { get; set; }
    
    	/// <summary>
    	/// 用户上次签到时间
    	/// </summary>
        public System.DateTime? UserSignTime { get; set; }
    
    }
}
