//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户动态头像
    /// </summary>
    public partial class VIPHead
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public int VIPHeadId { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public long? UserID { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public string HeadUrl { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsChecked { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    }
}
