//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonBBS.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 人才招聘
    /// </summary>
    public partial class ZhaoPin
    {
    	/// <summary>
    	/// 
    	/// </summary>
        public long ZhaoPinID { get; set; }
    
    	/// <summary>
    	/// 发布人
    	/// </summary>
        public string Publisher { get; set; }
    
    	/// <summary>
    	/// 招聘岗位
    	/// </summary>
        public string Gangwei { get; set; }
    
    	/// <summary>
    	/// 薪资待遇
    	/// </summary>
        public int? Money { get; set; }
    
    	/// <summary>
    	/// 学历要求（1不限2高中3中专4大专5本科6研究生7博士）
    	/// </summary>
        public int? Study { get; set; }
    
    	/// <summary>
    	/// 工作经验(1不限2：1-3年 3：3-5年 4：5-10年 5：10年以上）
    	/// </summary>
        public int? WorkHistory { get; set; }
    
    	/// <summary>
    	/// 工作地点
    	/// </summary>
        public string WorkPlace { get; set; }
    
    	/// <summary>
    	/// 公司名称
    	/// </summary>
        public string CName { get; set; }
    
    	/// <summary>
    	/// 公司Logo
    	/// </summary>
        public string CLogo { get; set; }
    
    	/// <summary>
    	/// 公司人数
    	/// </summary>
        public int? CPeople { get; set; }
    
    	/// <summary>
    	/// 公司认证
    	/// </summary>
        public int? CVip { get; set; }
    
    	/// <summary>
    	/// 公司简介
    	/// </summary>
        public string CDesc { get; set; }
    
    	/// <summary>
    	/// 职位描述照片
    	/// </summary>
        public string JobPic { get; set; }
    
    	/// <summary>
    	/// 职位描述文档
    	/// </summary>
        public string JobWord { get; set; }
    
    	/// <summary>
    	/// 联系方式
    	/// </summary>
        public string Contact { get; set; }
    
    	/// <summary>
    	/// 支付方式（1：vip积分(即金钱)支付     2：现金支付）
    	/// </summary>
        public int? PayType { get; set; }
    
    	/// <summary>
    	/// 是否支付（1已支付 0未支付）
    	/// </summary>
        public int? IsPay { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public System.DateTime? CreateTime { get; set; }
    
    	/// <summary>
    	/// 
    	/// </summary>
        public int? IsDelete { get; set; }
    
    	/// <summary>
    	/// 浏览量
    	/// </summary>
        public long? PVCount { get; set; }
    
    	/// <summary>
    	/// 职位要求
    	/// </summary>
        public string JobRequire { get; set; }
    
    	/// <summary>
    	/// 精华
    	/// </summary>
        public int? IsJinghua { get; set; }
    
    	/// <summary>
    	/// 热门
    	/// </summary>
        public int? IsRemen { get; set; }
    
    	/// <summary>
    	/// 置顶
    	/// </summary>
        public int? IsTop { get; set; }
    
    	/// <summary>
    	/// 工作性质（1 全职 2兼职）
    	/// </summary>
        public int? WorkeType { get; set; }
    
    	/// <summary>
    	/// 兼职周期
    	/// </summary>
        public string WorkTime { get; set; }
    
    	/// <summary>
    	/// 行业
    	/// </summary>
        public System.Guid? BelongJobTrade { get; set; }
    
    	/// <summary>
    	/// 职位
    	/// </summary>
        public System.Guid? BelongJob { get; set; }
    
    	/// <summary>
    	/// 职位福利
    	/// </summary>
        public string JobFuLi { get; set; }
    
    	/// <summary>
    	/// 招聘人数
    	/// </summary>
        public int? NeedCount { get; set; }
    
    	/// <summary>
    	/// 有效时间
    	/// </summary>
        public System.DateTime? ValidTime { get; set; }
    
    	/// <summary>
    	/// 更新时间
    	/// </summary>
        public System.DateTime? UpdateTime { get; set; }
    
    	/// <summary>
    	/// 更新人
    	/// </summary>
        public string UpdateUser { get; set; }
    
    }
}
